### ISSUE TITLE
Segmentation Step fails

### ISSUE THREAD

**Issue by PeterBehringer** [fedorov/PCampReview#85]
Traceback (most recent call last):
  File "/Users/peterbehringer/MyProjects/Modules/PCampReview/PCampReview.py", line 318, in setup
    effectButtonFrame.addWidget(slicer.util.findChildren(editBoxFrame,'WindowLevelEffectToolButton')[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/peterbehringer/MyProjects/Modules/PCampReview/PCampReview.py", line 202, in onTabWidgetClicked
    self.onStep3Selected()
  File "/Users/peterbehringer/MyProjects/Modules/PCampReview/PCampReview.py", line 1211, in onStep3Selected
    self.resetTranslate()
  File "/Users/peterbehringer/MyProjects/Modules/PCampReview/PCampReview.py", line 1930, in resetTranslate
    self.translateLR.value = 0
AttributeError: PCampReviewWidget instance has no attribute 'translateLR'

**Comment by che85** [comment]
To prevent such errors, we should create checks for existence of dependencies during loading of the module, since WindowLevelEffect is one dependency

**Comment by fedorov** [comment]
For now, this module is not publicly released, so we don't expect many users. It is ok to just make sure we document the fact that WindowLevelEffect is a prerequisite.

In the future, when this becomes an extension, there is an explicit dependency on WindowLevelEffect, so it should be handled by the standard extensions mechanisms (I am not sure, either the user is prompted to install the dependency, or it is installed automatically).

**Comment by fedorov** [comment]
this was resolved as part of the release
